### ISSUE TITLE
Выдача привилегий для PostgreSQL

### ISSUE THREAD

**Issue by VityaGoro** [SimpleCabinet/SimpleCabinetBackend#6]
При использовании следующей конфигурации:

![image](https://user-images.githubusercontent.com/32596459/103545471-0a160c00-4ebb-11eb-86ab-fa26770e1a58.png)

Лаунчсервер всё равно обращается к localhost:5432

[ERROR] org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

**Comment by VityaGoro** [comment]
Если база будет действительно на localhost:5432 - всё отлично работает.

**Comment by gravit0** [comment]
Конфигурация несколько отличается:
"addresses": [ "192.168.0.5" ],
"ports": ["6543"]

**Comment by VityaGoro** [comment]
Перекидывать и проверять лениво, в доке поправьте, если так действительно работает)
![image](https://user-images.githubusercontent.com/32596459/103545903-a93b0380-4ebb-11eb-88e5-288e60b0752c.png)

Спасибо!
