### ISSUE TITLE
Интеграция с другими

### ISSUE THREAD

**Issue by Linked-su** [SimpleCabinet/SimpleCabinetBackend#7]
Не знаю на какой стороне это лучше делать типо на лаунчсервере или самом модуле лк.
т.к лаунчер делает авторизацию через type: cabinet как насчет добавить под тип к нему request или json запрос
Идея в том что когда игрок регистрируется в основной cms(xenforo) то при вводе логина и пароля в самом лк делает запрос в по request и создает аккаунт в лк сам и в дальнейшем так же позволит авторизоваться таким же методом.

**Comment by gravit0** [comment]
Крайне низкая производительность и отсутствие дополнительных полей(вроде email). Используйте миграцию для перемещения старой БД в новую
При острой необходимости в синхронизации аккаунтов между CMS можете использовать самописные решения, когда регистрация в ЛК создает аккаунт в вашей CMS и наоборот
Обычно после миграции закрывают возможность регистрации на старой CMS(если это DLE/WordPress и подобное), либо оставляют регистрацию отдельно(форумы)

**Comment by Linked-su** [comment]
1. Если будет такая интеграция я думаю email не понадобится или его можно так же передавать через скрипт.
2. Проблема в разных видах хранения паролей.
3. Разве не лучше когда регистрация одна?

**Comment by gravit0** [comment]
Если среди поддерживаемых алгоритмов нет подходящего - реализуйте и делайте PR. Это поможет другим пользователям, кто мигрирует с этой же CMS
Потеря производительности на запросы к сайту огромна и не стоит того, что бы такой способ интеграции делать из коробки. И если такое необходимо значит вы что то делаете не так
