### ISSUE TITLE
MultiServer error

### ISSUE THREAD

**Issue by VityaGoro** [SimpleCabinet/SimpleCabinetBackend#8]
Приветствую!

Документация:
![image](https://user-images.githubusercontent.com/32596459/103811704-c6680180-5076-11eb-8585-f2523eca3f27.png)

Мой конфиг:
![image](https://user-images.githubusercontent.com/32596459/103811842-00d19e80-5077-11eb-9e29-fd8937c48cbf.png)

Ошибка:
[ERROR] com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.serverUUID

**Comment by Linked-su** [comment]
что за параметр all_servers и serverUUID? Ты че? Не видишь разницу?

ок, вот мой:
`  "deliveryProviders": {
    "luckperms": {
      "mySQLSource": {
        "address": "node.linked.su",
        "port": 3306,
        "username": "cabinetuse",
        "password": "iJ5qL2hX1mgP7k",
        "database": "cabinet?serverTimezone=UTC"
      },
    "sql": "INSERT INTO `luckperms_user_permissions` (`uuid`, `permission`, `value`, `server`, `world`, `expiry`, `contexts`) VALUES (?, ?, ?, ?, ?, ?, ?);",
    "type": "luckperms"
    },
    "event": {
      "multiserver": true,
      "list": ["e4df1419-1603-4f96-9488-9e2a7c7327af", "2ddf1d19-1603-4f96-9488-9e2a7c7327af"],
      "noAutoDelivery": true,
      "type": "event"
     }
  },`

**Comment by Linked-su** [comment]
Ты типо не видишь разницу?
ок, вот мой:
```
  "deliveryProviders": {
    "luckperms": {
      "mySQLSource": {
        "address": "localhost",
        "port": 3306,
        "username": "cabinetuse",
        "password": "тут пасс",
        "database": "cabinet?serverTimezone=UTC"
      },
    "sql": "INSERT INTO `luckperms_user_permissions` (`uuid`, `permission`, `value`, `server`, `world`, `expiry`, `contexts`) VALUES (?, ?, ?, ?, ?, ?, ?);",
    "type": "luckperms"
    },
    "event": {
      "multiserver": true,
      "list": ["e4df1419-1603-4f96-9488-9e2a7c7327af", "2ddf1d19-1603-4f96-9488-9e2a7c7327af"],
      "noAutoDelivery": true,
      "type": "event"
     }
  },
```

**Comment by VityaGoro** [comment]
Хэх, сорян, в ночь в глаза задолбился)

Благодарю)
